version: '3'

services:
  backend:
    image: backend
    container_name: backend
    build: ./backend/
    #restart: always
    ports:
      - 3080:3080

  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - 3000:80 # We need to map here for convenience, so we don't conflict with a potential possible local server
    environment:
      - BACKEND_IP=backend
      - BACKEND_PORT=3080
    depends_on:
      - backend
